import assert from "node:assert/strict";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { runCli, withTempHome } from "../../../workflows/_lib/tests/_cli-fixture.ts";

// Behavior tests for skills/pr/scripts/prompt-log.ts's `render` subcommand (issue #727 U-001).
// Each transcript is seeded as a real .claude/projects/<dir>/<sessionId>.jsonl file under a temp
// HOME, the same immediate-child layout resolveTranscript reads, so render finds it exactly the
// way it would against a real session.

const HERE = dirname(fileURLToPath(import.meta.url));
const SCRIPT = join(HERE, "..", "scripts", "prompt-log.ts");

/** Writes `lines` (each already a JSON string) as one .claude/projects/test-project/<sessionId>.jsonl
 * under `home`, standing in for a real session transcript. */
function seedTranscript(home: string, sessionId: string, lines: readonly string[]): string {
  const dir = join(home, ".claude", "projects", "test-project");
  mkdirSync(dir, { recursive: true });
  const path = join(dir, `${sessionId}.jsonl`);
  writeFileSync(path, lines.map((line) => `${line}\n`).join(""));
  return path;
}

const humanEntry = (content: string, timestamp: string): string =>
  JSON.stringify({
    type: "user",
    message: { role: "user", content },
    origin: { kind: "human" },
    promptSource: "typed",
    timestamp,
  });

const toolResultEntry = (timestamp: string): string =>
  JSON.stringify({
    type: "user",
    message: {
      role: "user",
      content: [
        {
          tool_use_id: "toolu_01AAAA",
          type: "tool_result",
          content: "result text",
          is_error: false,
        },
      ],
    },
    timestamp,
  });

const isMetaEntry = (timestamp: string): string =>
  JSON.stringify({
    type: "user",
    isMeta: true,
    message: {
      role: "user",
      content: "local-command-caveat: generated by a local command",
    },
    timestamp,
  });

const taskNotificationEntry = (timestamp: string): string =>
  JSON.stringify({
    type: "user",
    message: { role: "user", content: "task-notification: task-id abc123" },
    origin: { kind: "task-notification" },
    timestamp,
  });

const assistantEntry = (timestamp: string): string =>
  JSON.stringify({
    type: "assistant",
    message: { role: "assistant", content: [{ type: "text", text: "ok" }] },
    timestamp,
  });

// A single-character marker pair joined at runtime, so the source text never spells a
// contiguous "<tag>...</tag>" literal for the transcript's own pseudo-XML markers.
const LT = String.fromCharCode(60);
const GT = String.fromCharCode(62);

test("T-520 render keeps user entries whose origin.kind is human and drops tool results, isMeta entries, and task-notification origins", () => {
  withTempHome((home) => {
    const sessionId = "11111111-1111-1111-1111-111111111111";
    seedTranscript(home, sessionId, [
      humanEntry("Please do X", "2026-01-01T00:00:00.000Z"),
      toolResultEntry("2026-01-01T00:00:01.000Z"),
      isMetaEntry("2026-01-01T00:00:02.000Z"),
      taskNotificationEntry("2026-01-01T00:00:03.000Z"),
      assistantEntry("2026-01-01T00:00:04.000Z"),
    ]);
    const outPath = join(home, "out", "prompt-log.md");
    const run = runCli(SCRIPT, home, "", ["render", sessionId, "--out", outPath]);
    assert.equal(run.status, 0, `exit code (stderr: ${run.stderr})`);

    const stdout = JSON.parse(run.stdout) as { path: string; prompts: number; dropped: number };
    assert.equal(stdout.prompts, 1, "only the human entry is kept as a prompt");
    assert.equal(
      stdout.dropped,
      4,
      "the tool result, isMeta, task-notification, and assistant entries are dropped",
    );

    const markdown = readFileSync(outPath, "utf8");
    assert.match(markdown, /Please do X/, "the human prompt's text is written");
    assert.doesNotMatch(markdown, /toolu_01AAAA/, "the tool result is not written as a prompt");
    assert.doesNotMatch(
      markdown,
      /local-command-caveat/,
      "the isMeta entry is not written as a prompt",
    );
    assert.doesNotMatch(
      markdown,
      /task-notification/,
      "the task-notification entry is not written as a prompt",
    );
  });
});

test("T-521 render collapses a pasted_content body to a one-line marker carrying its character count and strips system-reminder blocks", () => {
  withTempHome((home) => {
    const sessionId = "22222222-2222-2222-2222-222222222222";
    const pastedBody = "line one of pasted text\nline two of pasted text";
    const reminderBody = "This is system-reminder content that must never reach the reviewer.";
    const content =
      `before ${LT}pasted_content id="a1b2"${GT}${pastedBody}${LT}/pasted_content${GT} middle ` +
      `${LT}system-reminder${GT}${reminderBody}${LT}/system-reminder${GT} after`;
    seedTranscript(home, sessionId, [humanEntry(content, "2026-01-01T00:00:00.000Z")]);
    const outPath = join(home, "prompt-log.md");
    const run = runCli(SCRIPT, home, "", ["render", sessionId, "--out", outPath]);
    assert.equal(run.status, 0, `exit code (stderr: ${run.stderr})`);

    const markdown = readFileSync(outPath, "utf8");
    const marker = `[pasted_content: ${pastedBody.length} chars]`;
    assert.match(markdown, /before .* middle .* after/s, "the surrounding text is kept");
    assert.ok(markdown.includes(marker), `the pasted_content body collapses to ${marker}`);
    assert.doesNotMatch(
      markdown,
      /line one of pasted text/,
      "the pasted_content body itself is not written",
    );
    assert.doesNotMatch(markdown, /system-reminder/, "the system-reminder tags are dropped");
    assert.doesNotMatch(
      markdown,
      /never reach the reviewer/,
      "the system-reminder body is dropped",
    );
  });
});

test("T-522 render with --since drops prompts before the bound except the last one before it, and keeps the rest in transcript order", () => {
  withTempHome((home) => {
    const sessionId = "33333333-3333-3333-3333-333333333333";
    seedTranscript(home, sessionId, [
      humanEntry("earliest prompt", "2026-01-01T00:00:00.000Z"),
      humanEntry("origin prompt", "2026-01-01T00:03:00.000Z"),
      humanEntry("boundary prompt", "2026-01-01T00:05:00.000Z"),
      humanEntry("latest prompt", "2026-01-01T00:10:00.000Z"),
    ]);
    const outPath = join(home, "prompt-log.md");
    const run = runCli(SCRIPT, home, "", [
      "render",
      sessionId,
      "--out",
      outPath,
      "--since",
      "2026-01-01T00:05:00.000Z",
    ]);
    assert.equal(run.status, 0, `exit code (stderr: ${run.stderr})`);

    const stdout = JSON.parse(run.stdout) as { prompts: number };
    assert.equal(
      stdout.prompts,
      3,
      "the last prompt before the bound, the boundary one, and the later one are kept",
    );

    const markdown = readFileSync(outPath, "utf8");
    assert.doesNotMatch(markdown, /earliest prompt/, "a prompt older than the origin is dropped");
    const originAt = markdown.indexOf("origin prompt");
    const boundaryAt = markdown.indexOf("boundary prompt");
    const latestAt = markdown.indexOf("latest prompt");
    // The branch is cut after the prompt that asked for the work, so that prompt always sits
    // just before --since.
    assert.ok(originAt >= 0, "the last prompt before --since is kept as the branch's origin");
    assert.ok(boundaryAt >= 0, "the boundary prompt (at --since) is kept");
    assert.ok(latestAt >= 0, "the latest prompt is kept");
    assert.ok(originAt < boundaryAt && boundaryAt < latestAt, "the kept prompts stay in transcript order");
  });
});

test("T-533 render with --since and no prompt at or after the bound keeps the last prompt before it and exits 0", () => {
  withTempHome((home) => {
    // #749: the work was asked for, the branch was cut, and no further prompt followed.
    const sessionId = "35353535-3535-3535-3535-353535353535";
    seedTranscript(home, sessionId, [
      humanEntry("unrelated earlier prompt", "2026-01-01T00:00:00.000Z"),
      humanEntry("start the fix", "2026-01-01T00:04:00.000Z"),
    ]);
    const outPath = join(home, "prompt-log.md");
    const run = runCli(SCRIPT, home, "", [
      "render",
      sessionId,
      "--out",
      outPath,
      "--since",
      "2026-01-01T00:05:00.000Z",
    ]);
    assert.equal(run.status, 0, `exit code (stderr: ${run.stderr})`);
    const stdout = JSON.parse(run.stdout) as { prompts: number };
    assert.equal(stdout.prompts, 1);
    const markdown = readFileSync(outPath, "utf8");
    assert.match(markdown, /start the fix/);
    assert.doesNotMatch(markdown, /unrelated earlier prompt/);
  });
});

test("T-523 render exits 1 with an empty stdout when a non-empty transcript holds no human prompt, and the same transcript plus one human prompt exits 0", () => {
  withTempHome((home) => {
    const noHumanId = "44444444-4444-4444-4444-444444444444";
    const nonHumanLines = [
      toolResultEntry("2026-01-01T00:00:00.000Z"),
      isMetaEntry("2026-01-01T00:00:01.000Z"),
      taskNotificationEntry("2026-01-01T00:00:02.000Z"),
      assistantEntry("2026-01-01T00:00:03.000Z"),
    ];
    seedTranscript(home, noHumanId, nonHumanLines);
    const noHumanOut = join(home, "no-human.md");
    const noHumanRun = runCli(SCRIPT, home, "", ["render", noHumanId, "--out", noHumanOut]);
    assert.equal(
      noHumanRun.status,
      1,
      `exit code on zero human prompts (stderr: ${noHumanRun.stderr})`,
    );
    assert.equal(noHumanRun.stdout, "", "stdout is empty when no human prompt is found");

    // Positive control: the same transcript plus one human prompt exits 0 with that one prompt.
    const withHumanId = "55555555-5555-5555-5555-555555555555";
    seedTranscript(home, withHumanId, [
      ...nonHumanLines,
      humanEntry("the only human prompt", "2026-01-01T00:00:04.000Z"),
    ]);
    const withHumanOut = join(home, "with-human.md");
    const withHumanRun = runCli(SCRIPT, home, "", ["render", withHumanId, "--out", withHumanOut]);
    assert.equal(
      withHumanRun.status,
      0,
      `exit code with one human prompt (stderr: ${withHumanRun.stderr})`,
    );
    const stdout = JSON.parse(withHumanRun.stdout) as { prompts: number };
    assert.equal(stdout.prompts, 1, "exactly the one human prompt is kept");
  });
});
