#!/usr/bin/env node
/// <reference types="node" />
// Usage: update-index.ts [dr-directory]
//
// Regenerates <dr-dir>/README.md from the Decision Record files.
// stdout: path to the updated index file
// stderr: directory not found etc. with exit 1
//
// TypeScript port of the retired Python update-index, in the header/entry shape
// skills/_lib/harness_hash.ts, skills/dr/scripts/dr_common.ts, skills/dr/scripts/pre-check.ts,
// and skills/dr/scripts/validate-dr.ts already use: a plain shebang + reference-types + Usage
// header, named exports for the pieces a test can drive directly, and the CLI's own
// process.exit(main()) guarded by workflows/_lib/entry-point.ts's isMainModule so importing
// this module for its exports never runs the CLI as a side effect.
//
// Contract: the retired Python update-index's STATUS_SECTIONS, HEADER, FOOTER, parse_dr, and
// main. STATUS_SECTIONS is exported -- skills/dr/tests/update-index.test.ts's T-210 reads it to
// pick a status value that starts with none of its keys, the same way the section-bucketing
// loop below does. FOOTER's own generator-credit line reads "update-index.ts", an intended
// difference from the retired Python original's own name that
// skills/dr/tests/fixtures/update-index-cases.json's frozen README records on that one line.
//
// Exercised by skills/dr/tests/update-index.test.ts.
import { existsSync, readFileSync, renameSync, statSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { basename, join } from "node:path";
import {
  fail,
  filesUnder,
  gitTopLevel,
  guardSkillDir,
  localDate,
  resolveDrDir,
  splitFrontmatter,
} from "./dr_common.ts";
import { isMainModule } from "../../../workflows/_lib/entry-point.ts";

// The retired Python update-index's STATUS_SECTIONS: the By Status heading text keyed by the
// status-value prefix a DR's frontmatter status must startWith to land in that section, in the same
// proposed/accepted/deprecated/superseded/rejected order the README's By Status headings use.
export const STATUS_SECTIONS = [
  ["proposed", "Proposed"],
  ["accepted", "Accepted"],
  ["deprecated", "Deprecated"],
  ["superseded", "Superseded"],
  ["rejected", "Rejected"],
] as const;

// The retired Python update-index's HEADER: the DR List table's opening, verbatim through the
// header separator row -- main() appends each row's text directly after this string's trailing
// newline, with no blank line in between.
export const HEADER = `# Decision Records

This directory contains important decisions about the project.

## DR List

| Number | Title | Status | Date |
|--------|-------|--------|------|
`;

// The retired Python update-index's FOOTER, with its own {update_date} placeholder replaced the
// same way Python's str.format(update_date=...) does. "update-index.ts" on the last line is the
// one intended difference from the retired original's own FOOTER -- see this file's header
// comment.
export const FOOTER = `## About MADR Format

This project uses [MADR (Markdown Any Decision Records)](https://adr.github.io/madr/) format, v4.

### How to Create a Decision Record

\`\`\`bash
/dr "Decision Title"
\`\`\`

### Status Meanings

- **Proposed**: Awaiting review
- **Accepted**: Approved, implementing or completed
- **Rejected**: Considered but not adopted
- **Deprecated**: Retired without a replacement DR
- **Superseded**: Replaced by another DR (e.g. \`superseded by DR-NNNN\`)

---

*Last updated: {update_date}*
*Auto-generated by: update-index.ts*
`;

/** The retired Python update-index's parse_dr: (title, status, date) from frontmatter and the
 * first `# ` heading -- status defaults to "proposed" and date to "Not set" when the frontmatter
 * carries neither, the same `status or "proposed"` / `date_str or "Not set"` fallback Python's
 * falsy-empty-string check applies. */
export function parseDr(path: string): [title: string, status: string, date: string] {
  const [frontmatter, body] = splitFrontmatter(readFileSync(path, "utf8"));
  const statusLine = frontmatter.find((line) => line.startsWith("status:"));
  const status = statusLine
    ? statusLine.slice("status:".length).trim().replace(/^"|"$/g, "")
    : "";
  const dateLine = frontmatter.find((line) => line.startsWith("date:"));
  const dateStr = dateLine ? dateLine.slice("date:".length).trim().replace(/^"|"$/g, "") : "";
  const titleLine = body.find((line) => line.startsWith("# "));
  const title = titleLine ? titleLine.slice(2) : "";
  return [title, status || "proposed", dateStr || "Not set"];
}

/** The DR List rows and the By Status buckets one pass over drDir's DR files produces: `rows`
 * carries the table lines main() joins under HEADER, and `byStatus` carries each
 * STATUS_SECTIONS key's [number, title] pairs for the By Status loop in main() to sort and
 * render. */
interface CollectRowsResult {
  rows: string[];
  byStatus: Map<string, Array<[number: string, title: string]>>;
}

// The retired Python update-index's rglob("[0-9][0-9][0-9][0-9]-*.md").
const DR_FILE_NAME = /^\d{4}-.*\.md$/;

/** Scans drDir for DR files (sorted by full path) and, for each, appends its DR
 * List row and buckets its [number, title] under the first STATUS_SECTIONS key its status
 * starts with. Called from main(). */
function collectRows(drDir: string): CollectRowsResult {
  const rows: string[] = [];
  const byStatus = new Map<string, Array<[number: string, title: string]>>(
    STATUS_SECTIONS.map(([key]) => [key, []]),
  );
  for (const drFile of filesUnder(drDir, (name) => DR_FILE_NAME.test(name)).sort()) {
    const name = basename(drFile);
    const number = name.slice(0, 4);
    const [title, status, date] = parseDr(drFile);
    rows.push(`| [${number}](${name}) | ${title} | ${status} | ${date} |`);
    for (const [key] of STATUS_SECTIONS) {
      const bucket = byStatus.get(key);
      if (bucket && status.startsWith(key)) {
        bucket.push([number, title]);
        break;
      }
    }
  }
  return { rows, byStatus };
}

/** Python's sorted() on (number, title) tuples: number first, title as tiebreaker -- a
 * tiebreaker that in practice never triggers, since a DR's 4-digit number is unique. Called
 * from main() as the By Status entries' sort comparator. */
function compareEntries(
  [numA, titleA]: [number: string, title: string],
  [numB, titleB]: [number: string, title: string],
): number {
  if (numA !== numB) return numA < numB ? -1 : 1;
  if (titleA < titleB) return -1;
  if (titleA > titleB) return 1;
  return 0;
}

// Python's main() takes no argv of its own beyond the optional dr-directory positional
// (sys.argv[1] if len(sys.argv) > 1 else None), the same process.argv.slice(2) convention
// pre-check.ts's and validate-dr.ts's main(argv) already use.
export function main(argv: string[]): number {
  const arg = argv[0];
  const drDir = resolveDrDir(
    process.env,
    arg,
    process.env.DR_DIR || arg ? { status: 0, stdout: "" } : gitTopLevel(),
  );
  if (drDir === null) {
    fail(
      "Error: not inside a git repository. Decision Records require" +
        " <git-root>/docs/decisions/. Set DR_DIR env var to override.",
    );
  }
  if (!existsSync(drDir) || !statSync(drDir).isDirectory()) {
    fail(`Error: directory not found: ${drDir}`);
  }
  guardSkillDir(drDir, "Set DR_DIR env var or pass an explicit DR archive path.");

  const { rows, byStatus } = collectRows(drDir);

  const parts: string[] = [HEADER + rows.join("\n"), "\n## By Status\n"];
  for (const [key, heading] of STATUS_SECTIONS) {
    const entries = byStatus.get(key) ?? [];
    if (entries.length === 0) continue;
    const sorted = [...entries].sort(compareEntries);
    const entryLines = sorted.map(([num, title]) => `- **${num}**: ${title}`).join("\n");
    parts.push(`### ${heading}\n\n${entryLines}\n`);
  }
  const updateDate = localDate(new Date());
  parts.push(FOOTER.replace("{update_date}", updateDate));

  const indexFile = join(drDir, "README.md");
  // tempfile.mkstemp(dir=dr_dir) + Path(temp_path).replace(index_file): a temp file in the
  // same directory (so the rename below is same-filesystem, hence atomic), named uniquely
  // enough that a concurrent run of this script never collides on it.
  const tempPath = join(drDir, `.README.md.${randomBytes(8).toString("hex")}.tmp`);
  writeFileSync(tempPath, parts.join("\n"), "utf8");
  renameSync(tempPath, indexFile);

  process.stdout.write(`${indexFile}\n`);
  return 0;
}

if (isMainModule(import.meta.url)) {
  process.exit(main(process.argv.slice(2)));
}
