#!/usr/bin/env node
/// <reference types="node" />
// Usage: update-index.ts [dr-directory]
//
// Regenerates <dr-dir>/README.md from the Decision Record files.
// stdout: path to the updated index file
// stderr: directory not found etc. with exit 1
//
// TypeScript port of the retired Python update-index, in the header/entry shape
// skills/_lib/harness_hash.ts, skills/dr/scripts/dr_common.ts, skills/dr/scripts/pre-check.ts,
// and skills/dr/scripts/validate-dr.ts already use: a plain shebang + reference-types + Usage
// header, named exports for the pieces a test can drive directly, and the CLI's own
// process.exit(main()) guarded by workflows/_lib/entry-point.ts's isMainModule so importing
// this module for its exports never runs the CLI as a side effect.
//
// Contract: the retired Python update-index's STATUS_SECTIONS, HEADER, FOOTER, parse_dr, and
// main. STATUS_SECTIONS is exported -- skills/dr/tests/update-index.test.ts's T-210 reads it to
// pick a status value that starts with none of its keys, the same way the section-bucketing
// loop below does. FOOTER's own generator-credit line reads "update-index.ts", an intended
// difference from the retired Python original's own name that
// skills/dr/tests/fixtures/update-index-cases.json's frozen README records on that one line.
//
// Exercised by skills/dr/tests/update-index.test.ts.
import { existsSync, readFileSync, readdirSync, renameSync, statSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { basename, join } from "node:path";
import { spawnSync } from "node:child_process";
import { fail, guardSkillDir, resolveDrDir, splitFrontmatter, type GitTopLevelResult } from "./dr_common.ts";
import { isMainModule } from "../../../workflows/_lib/entry-point.ts";

// The retired Python update-index's STATUS_SECTIONS: the By Status heading text keyed by the
// status-value prefix a DR's frontmatter status must startWith to land in that section, in the same
// proposed/accepted/deprecated/superseded/rejected order the README's By Status headings use.
export const STATUS_SECTIONS = [
  ["proposed", "Proposed"],
  ["accepted", "Accepted"],
  ["deprecated", "Deprecated"],
  ["superseded", "Superseded"],
  ["rejected", "Rejected"],
] as const;

// The retired Python update-index's HEADER: the DR List table's opening, verbatim through the
// header separator row -- main() appends each row's text directly after this string's trailing
// newline, with no blank line in between.
export const HEADER = `# Decision Records

This directory contains important decisions about the project.

## DR List

| Number | Title | Status | Date |
|--------|-------|--------|------|
`;

// The retired Python update-index's FOOTER, with its own {update_date} placeholder replaced the
// same way Python's str.format(update_date=...) does. "update-index.ts" on the last line is the
// one intended difference from the retired original's own FOOTER -- see this file's header
// comment.
export const FOOTER = `## About MADR Format

This project uses [MADR (Markdown Any Decision Records)](https://adr.github.io/madr/) format, v4.

### How to Create a Decision Record

\`\`\`bash
/dr "Decision Title"
\`\`\`

### Status Meanings

- **Proposed**: Awaiting review
- **Accepted**: Approved, implementing or completed
- **Rejected**: Considered but not adopted
- **Deprecated**: Retired without a replacement DR
- **Superseded**: Replaced by another DR (e.g. \`superseded by DR-NNNN\`)

---

*Last updated: {update_date}*
*Auto-generated by: update-index.ts*
`;

/** The retired Python update-index's parse_dr: (title, status, date) from frontmatter and the
 * first `# ` heading -- status defaults to "proposed" and date to "Not set" when the frontmatter
 * carries neither, the same `status or "proposed"` / `date_str or "Not set"` fallback Python's
 * falsy-empty-string check applies. */
export function parseDr(path: string): [title: string, status: string, date: string] {
  const [frontmatter, body] = splitFrontmatter(readFileSync(path, "utf8"));
  const statusLine = frontmatter.find((line) => line.startsWith("status:"));
  const status = statusLine
    ? statusLine.slice("status:".length).trim().replace(/^"|"$/g, "")
    : "";
  const dateLine = frontmatter.find((line) => line.startsWith("date:"));
  const dateStr = dateLine ? dateLine.slice("date:".length).trim().replace(/^"|"$/g, "") : "";
  const titleLine = body.find((line) => line.startsWith("# "));
  const title = titleLine ? titleLine.slice(2) : "";
  return [title, status || "proposed", dateStr || "Not set"];
}

/** The retired Python update-index's `dr_dir.rglob("[0-9][0-9][0-9][0-9]-*.md")`: every file at
 * any depth under dir whose own name is 4 digits, a dash, then anything, ending in .md -- as full
 * paths, for the caller to sort (rglob's Path results carry no ordering of their own until
 * sorted). */
function drFilesUnder(dir: string): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      found.push(...drFilesUnder(full));
    } else if (entry.isFile() && /^\d{4}-.*\.md$/.test(entry.name)) {
      found.push(full);
    }
  }
  return found;
}

/** `git rev-parse --show-toplevel`, read only when resolveDrDir needs it (DR_DIR unset and no
 * CLI argument) -- mirroring pre-check.ts's own gitTopLevel(), duplicated here rather than
 * shared since it is a few lines wrapping a single spawnSync call. */
function gitTopLevel(): GitTopLevelResult {
  const result = spawnSync("git", ["rev-parse", "--show-toplevel"], { encoding: "utf8" });
  return { status: result.status, stdout: result.stdout ?? "", error: result.error };
}

// Python's main() takes no argv of its own beyond the optional dr-directory positional
// (sys.argv[1] if len(sys.argv) > 1 else None), the same process.argv.slice(2) convention
// pre-check.ts's and validate-dr.ts's main(argv) already use.
export function main(argv: string[]): number {
  const arg = argv[0];
  const drDir = resolveDrDir(
    process.env,
    arg,
    process.env.DR_DIR || arg ? { status: 0, stdout: "" } : gitTopLevel(),
  );
  if (drDir === null) {
    fail(
      "Error: not inside a git repository. Decision Records require" +
        " <git-root>/docs/decisions/. Set DR_DIR env var to override.",
    );
  }
  if (!existsSync(drDir) || !statSync(drDir).isDirectory()) {
    fail(`Error: directory not found: ${drDir}`);
  }
  guardSkillDir(drDir, "Set DR_DIR env var or pass an explicit DR archive path.");

  const rows: string[] = [];
  const byStatus = new Map<string, Array<[number: string, title: string]>>(
    STATUS_SECTIONS.map(([key]) => [key, []]),
  );
  for (const drFile of drFilesUnder(drDir).sort()) {
    const name = basename(drFile);
    const number = name.slice(0, 4);
    const [title, status, date] = parseDr(drFile);
    rows.push(`| [${number}](${name}) | ${title} | ${status} | ${date} |`);
    for (const [key] of STATUS_SECTIONS) {
      const bucket = byStatus.get(key);
      if (bucket && status.startsWith(key)) {
        bucket.push([number, title]);
        break;
      }
    }
  }

  const parts: string[] = [HEADER + rows.join("\n"), "\n## By Status\n"];
  for (const [key, heading] of STATUS_SECTIONS) {
    const entries = byStatus.get(key) ?? [];
    if (entries.length === 0) continue;
    // Python's sorted() on (number, title) tuples: number first, title as tiebreaker -- a
    // tiebreaker that in practice never triggers, since a DR's 4-digit number is unique.
    const sorted = [...entries].sort(([numA, titleA], [numB, titleB]) =>
      numA !== numB ? (numA < numB ? -1 : 1) : titleA < titleB ? -1 : titleA > titleB ? 1 : 0,
    );
    const entryLines = sorted.map(([num, title]) => `- **${num}**: ${title}`).join("\n");
    parts.push(`### ${heading}\n\n${entryLines}\n`);
  }
  const now = new Date();
  const updateDate = [
    String(now.getFullYear()).padStart(4, "0"),
    String(now.getMonth() + 1).padStart(2, "0"),
    String(now.getDate()).padStart(2, "0"),
  ].join("-");
  parts.push(FOOTER.replace("{update_date}", updateDate));

  const indexFile = join(drDir, "README.md");
  // tempfile.mkstemp(dir=dr_dir) + Path(temp_path).replace(index_file): a temp file in the
  // same directory (so the rename below is same-filesystem, hence atomic), named uniquely
  // enough that a concurrent run of this script never collides on it.
  const tempPath = join(drDir, `.README.md.${randomBytes(8).toString("hex")}.tmp`);
  writeFileSync(tempPath, parts.join("\n"), "utf8");
  renameSync(tempPath, indexFile);

  process.stdout.write(`${indexFile}\n`);
  return 0;
}

if (isMainModule(import.meta.url)) {
  process.exit(main(process.argv.slice(2)));
}
