#!/bin/bash
# ADR Index Update Script
# Usage: update-index.sh [adr-directory]

set -euo pipefail

ADR_DIR="${1:-docs/adr}"

if [ ! -d "$ADR_DIR" ]; then
  echo "❌ Error: Directory not found: $ADR_DIR"
  exit 1
fi

INDEX_FILE="$ADR_DIR/README.md"

# Color definitions
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 ADR Index Update: $ADR_DIR"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Temporary files
TEMP_FILE=$(mktemp)
TEMP_PROPOSED=$(mktemp)
TEMP_ACCEPTED=$(mktemp)
TEMP_DEPRECATED=$(mktemp)
TEMP_SUPERSEDED=$(mktemp)

# Cleanup
trap "rm -f $TEMP_FILE $TEMP_PROPOSED $TEMP_ACCEPTED $TEMP_DEPRECATED $TEMP_SUPERSEDED" EXIT

# Header
cat > "$TEMP_FILE" <<'EOF'
# Architecture Decision Records

This directory contains important decisions about the project's architecture.

## ADR List

| Number | Title | Status | Date |
|--------|-------|--------|------|
EOF

while IFS= read -r adr_file; do
  # Extract number from filename
  FILENAME=$(basename "$adr_file")
  NUMBER=$(echo "$FILENAME" | grep -oE '^[0-9]{4}')

  # Extract title (first # line)
  TITLE=$(grep -m 1 '^# ' "$adr_file" | sed 's/^# //')

  # Extract status
  STATUS=$(grep -m 1 '^- Status:' "$adr_file" | sed 's/^- Status: //' | tr -d ' ')
  STATUS=${STATUS:-proposed}

  # Extract date
  DATE=$(grep -m 1 '^- Date:' "$adr_file" | sed 's/^- Date: //' | tr -d ' ')
  DATE=${DATE:-Not set}

  # Add table row
  echo "| [$NUMBER]($FILENAME) | $TITLE | $STATUS | $DATE |" >> "$TEMP_FILE"

  # Status-based aggregation (file output)
  case "$STATUS" in
    proposed)
      echo "$NUMBER|$TITLE" >> "$TEMP_PROPOSED"
      ;;
    accepted)
      echo "$NUMBER|$TITLE" >> "$TEMP_ACCEPTED"
      ;;
    deprecated)
      echo "$NUMBER|$TITLE" >> "$TEMP_DEPRECATED"
      ;;
    superseded)
      echo "$NUMBER|$TITLE" >> "$TEMP_SUPERSEDED"
      ;;
  esac
done < <(find "$ADR_DIR" -name "[0-9][0-9][0-9][0-9]-*.md" -type f | sort)

# Status-based sections
cat >> "$TEMP_FILE" <<'EOF'

## By Status

EOF

# Proposed
if [ -s "$TEMP_PROPOSED" ]; then
  echo "### Proposed" >> "$TEMP_FILE"
  echo "" >> "$TEMP_FILE"
  while IFS='|' read -r num title; do
    echo "- **$num**: $title" >> "$TEMP_FILE"
  done < <(sort "$TEMP_PROPOSED")
  echo "" >> "$TEMP_FILE"
fi

# Accepted
if [ -s "$TEMP_ACCEPTED" ]; then
  echo "### Accepted" >> "$TEMP_FILE"
  echo "" >> "$TEMP_FILE"
  while IFS='|' read -r num title; do
    echo "- **$num**: $title" >> "$TEMP_FILE"
  done < <(sort "$TEMP_ACCEPTED")
  echo "" >> "$TEMP_FILE"
fi

# Deprecated
if [ -s "$TEMP_DEPRECATED" ]; then
  echo "### Deprecated" >> "$TEMP_FILE"
  echo "" >> "$TEMP_FILE"
  while IFS='|' read -r num title; do
    echo "- **$num**: $title" >> "$TEMP_FILE"
  done < <(sort "$TEMP_DEPRECATED")
  echo "" >> "$TEMP_FILE"
fi

# Superseded
if [ -s "$TEMP_SUPERSEDED" ]; then
  echo "### Superseded" >> "$TEMP_FILE"
  echo "" >> "$TEMP_FILE"
  while IFS='|' read -r num title; do
    echo "- **$num**: $title" >> "$TEMP_FILE"
  done < <(sort "$TEMP_SUPERSEDED")
  echo "" >> "$TEMP_FILE"
fi

# Footer
cat >> "$TEMP_FILE" <<'EOF'
## About MADR Format

This project uses [MADR (Markdown Architecture Decision Records)](https://adr.github.io/madr/) format.

### How to Create an ADR

```bash
/adr "Decision Title"
```

### Status Meanings

- **Proposed**: Awaiting review
- **Accepted**: Approved, implementing or completed
- **Deprecated**: Better alternative found
- **Superseded**: Replaced by another ADR

---

*Last updated: {{UPDATE_DATE}}*
*Auto-generated by: update-index.sh*
EOF

# Date replacement
UPDATE_DATE=$(date +%Y-%m-%d)
sed -i.bak "s/{{UPDATE_DATE}}/$UPDATE_DATE/g" "$TEMP_FILE"
rm -f "$TEMP_FILE.bak"

# Replace file
mv "$TEMP_FILE" "$INDEX_FILE"

echo -e "${GREEN}✅ Index update complete: $INDEX_FILE${NC}"
echo ""
echo "📊 Statistics:"
echo "  Proposed: $(wc -l < "$TEMP_PROPOSED" | tr -d ' ')"
echo "  Accepted: $(wc -l < "$TEMP_ACCEPTED" | tr -d ' ')"
echo "  Deprecated: $(wc -l < "$TEMP_DEPRECATED" | tr -d ' ')"
echo "  Superseded: $(wc -l < "$TEMP_SUPERSEDED" | tr -d ' ')"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
