#!/usr/bin/env node
/// <reference types="node" />
// Usage: update-index.ts [dr-directory]
//
// Regenerates <dr-dir>/README.md from the Decision Record files.
// stdout: path to the updated index file
// stderr: directory not found etc. with exit 1
//
// 退役した Python 版 update-index の TypeScript 移植。header/entry の形は
// skills/_lib/harness_hash.ts、skills/dr/scripts/dr_common.ts、skills/dr/scripts/pre-check.ts、
// skills/dr/scripts/validate-dr.ts が既に使っているものと同じ: 素直な shebang +
// reference-types + Usage ヘッダー、テストが直接動かせる部分は named export にし、CLI 自身の
// process.exit(main()) は workflows/_lib/entry-point.ts の isMainModule でガードする。これに
// より、この module を export 目当てで import しても CLI が副作用として動くことはない。
//
// Contract: 退役した Python 版 update-index の STATUS_SECTIONS、HEADER、FOOTER、parse_dr、
// main。STATUS_SECTIONS は export されており、skills/dr/tests/update-index.test.ts の T-210 が
// これを import して、下の section-bucketing loop と同じやり方でどのキーにも startsWith しない
// status 値を選ぶ。FOOTER 自身の generator-credit 行は "update-index.ts" と読み、これは
// 退役した Python 版自身の名前とは意図して異なる差分であり、
// skills/dr/tests/fixtures/update-index-cases.json が凍結した README ではその 1 行に現れる。
//
// skills/dr/tests/update-index.test.ts が検証する。
import { existsSync, readFileSync, readdirSync, renameSync, statSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { basename, join } from "node:path";
import { spawnSync } from "node:child_process";
import { fail, guardSkillDir, resolveDrDir, splitFrontmatter, type GitTopLevelResult } from "./dr_common.ts";
import { isMainModule } from "../../../workflows/_lib/entry-point.ts";

// 退役した Python 版 update-index の STATUS_SECTIONS: By Status 見出しのテキストを、その
// DR の frontmatter の status がどの接頭辞に startWith するとその section に入るかという
// キーで引く。README の By Status 見出しと同じ
// proposed/accepted/deprecated/superseded/rejected の順で並ぶ。
export const STATUS_SECTIONS = [
  ["proposed", "Proposed"],
  ["accepted", "Accepted"],
  ["deprecated", "Deprecated"],
  ["superseded", "Superseded"],
  ["rejected", "Rejected"],
] as const;

// 退役した Python 版 update-index の HEADER: DR List テーブルの冒頭を、ヘッダー区切り行まで
// そのまま持つ -- main() は各行のテキストをこの文字列の末尾改行の直後にそのまま続け、間に空
// 行は入らない。
export const HEADER = `# Decision Records

This directory contains important decisions about the project.

## DR List

| Number | Title | Status | Date |
|--------|-------|--------|------|
`;

// 退役した Python 版 update-index の FOOTER。{update_date} プレースホルダーは Python の
// str.format(update_date=...) と同じやり方で置き換える。最後の行の "update-index.ts" が
// 退役した Python 版自身の FOOTER との唯一の意図した違いである -- このファイルの header
// comment を参照。
export const FOOTER = `## About MADR Format

This project uses [MADR (Markdown Any Decision Records)](https://adr.github.io/madr/) format, v4.

### How to Create a Decision Record

\`\`\`bash
/dr "Decision Title"
\`\`\`

### Status Meanings

- **Proposed**: Awaiting review
- **Accepted**: Approved, implementing or completed
- **Rejected**: Considered but not adopted
- **Deprecated**: Retired without a replacement DR
- **Superseded**: Replaced by another DR (e.g. \`superseded by DR-NNNN\`)

---

*Last updated: {update_date}*
*Auto-generated by: update-index.ts*
`;

/** 退役した Python 版 update-index の parse_dr: frontmatter と最初の `# ` 見出しから
 * (title, status, date) を得る -- frontmatter がどちらも持たないとき、status は
 * "proposed" に、date は "Not set" に落ちる。これは Python の falsy な空文字列チェックが
 * そうする `status or "proposed"` / `date_str or "Not set"` のフォールバックと同じである。 */
export function parseDr(path: string): [title: string, status: string, date: string] {
  const [frontmatter, body] = splitFrontmatter(readFileSync(path, "utf8"));
  const statusLine = frontmatter.find((line) => line.startsWith("status:"));
  const status = statusLine
    ? statusLine.slice("status:".length).trim().replace(/^"|"$/g, "")
    : "";
  const dateLine = frontmatter.find((line) => line.startsWith("date:"));
  const dateStr = dateLine ? dateLine.slice("date:".length).trim().replace(/^"|"$/g, "") : "";
  const titleLine = body.find((line) => line.startsWith("# "));
  const title = titleLine ? titleLine.slice(2) : "";
  return [title, status || "proposed", dateStr || "Not set"];
}

/** 退役した Python 版 update-index の `dr_dir.rglob("[0-9][0-9][0-9][0-9]-*.md")`: dir 配下
 * のあらゆる深さにあるファイルのうち、自身の名前が 4 桁の数字・ダッシュ・任意の文字列で
 * .md に終わるものをすべて、フルパスとして返す -- ソートは呼び出し側が行う (rglob が返す
 * Path はソートするまで順序を持たない)。 */
function drFilesUnder(dir: string): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      found.push(...drFilesUnder(full));
    } else if (entry.isFile() && /^\d{4}-.*\.md$/.test(entry.name)) {
      found.push(full);
    }
  }
  return found;
}

/** `git rev-parse --show-toplevel`。resolveDrDir がこれを必要とするとき (DR_DIR 未設定かつ
 * CLI 引数無し) だけ読む -- pre-check.ts 自身の gitTopLevel() をそのまま踏襲している。1 つの
 * spawnSync 呼び出しを包むだけの数行なので、共有せずここでも複製している。 */
function gitTopLevel(): GitTopLevelResult {
  const result = spawnSync("git", ["rev-parse", "--show-toplevel"], { encoding: "utf8" });
  return { status: result.status, stdout: result.stdout ?? "", error: result.error };
}

// Python の main() は dr-directory という省略可能な positional 以外の argv を取らない
// (sys.argv[1] if len(sys.argv) > 1 else None)。pre-check.ts と validate-dr.ts の main(argv) が
// 既に使っている process.argv.slice(2) の慣習と同じである。
export function main(argv: string[]): number {
  const arg = argv[0];
  const drDir = resolveDrDir(
    process.env,
    arg,
    process.env.DR_DIR || arg ? { status: 0, stdout: "" } : gitTopLevel(),
  );
  if (drDir === null) {
    fail(
      "Error: not inside a git repository. Decision Records require" +
        " <git-root>/docs/decisions/. Set DR_DIR env var to override.",
    );
  }
  if (!existsSync(drDir) || !statSync(drDir).isDirectory()) {
    fail(`Error: directory not found: ${drDir}`);
  }
  guardSkillDir(drDir, "Set DR_DIR env var or pass an explicit DR archive path.");

  const rows: string[] = [];
  const byStatus = new Map<string, Array<[number: string, title: string]>>(
    STATUS_SECTIONS.map(([key]) => [key, []]),
  );
  for (const drFile of drFilesUnder(drDir).sort()) {
    const name = basename(drFile);
    const number = name.slice(0, 4);
    const [title, status, date] = parseDr(drFile);
    rows.push(`| [${number}](${name}) | ${title} | ${status} | ${date} |`);
    for (const [key] of STATUS_SECTIONS) {
      const bucket = byStatus.get(key);
      if (bucket && status.startsWith(key)) {
        bucket.push([number, title]);
        break;
      }
    }
  }

  const parts: string[] = [HEADER + rows.join("\n"), "\n## By Status\n"];
  for (const [key, heading] of STATUS_SECTIONS) {
    const entries = byStatus.get(key) ?? [];
    if (entries.length === 0) continue;
    // Python の sorted() が (number, title) のタプルに対して行うのと同じ: number を優先し
    // title を tiebreaker にするが、DR の 4 桁番号は一意なので実際には tiebreaker が働く
    // ことはない。
    const sorted = [...entries].sort(([numA, titleA], [numB, titleB]) =>
      numA !== numB ? (numA < numB ? -1 : 1) : titleA < titleB ? -1 : titleA > titleB ? 1 : 0,
    );
    const entryLines = sorted.map(([num, title]) => `- **${num}**: ${title}`).join("\n");
    parts.push(`### ${heading}\n\n${entryLines}\n`);
  }
  const now = new Date();
  const updateDate = [
    String(now.getFullYear()).padStart(4, "0"),
    String(now.getMonth() + 1).padStart(2, "0"),
    String(now.getDate()).padStart(2, "0"),
  ].join("-");
  parts.push(FOOTER.replace("{update_date}", updateDate));

  const indexFile = join(drDir, "README.md");
  // tempfile.mkstemp(dir=dr_dir) + Path(temp_path).replace(index_file): 同じディレクトリ内の
  // temp file (これにより下の rename は同一ファイルシステム内になり atomic になる) を、この
  // script の並行実行が衝突しない程度に一意な名前で作る。
  const tempPath = join(drDir, `.README.md.${randomBytes(8).toString("hex")}.tmp`);
  writeFileSync(tempPath, parts.join("\n"), "utf8");
  renameSync(tempPath, indexFile);

  process.stdout.write(`${indexFile}\n`);
  return 0;
}

if (isMainModule(import.meta.url)) {
  process.exit(main(process.argv.slice(2)));
}
